src/qcos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from qcos.base.views import DioceseCreateView, DioceseDeleteView, DioceseDetailView, DioceseListView, DioceseUpdateView
from qcos.base.views import DistrictCreateView, DistrictUpdateView, DistrictDeleteView, DistrictDetailView
from qcos.base.views import ClanCreateView, ClanDetailView, ClanDeleteView, ClanUpdateView, CampCreateView
from qcos.base.views import UserListView, UserCreateView, UserUpdateView, UserDeleteView, OrganizerListView
from qcos.base.views import OrganizerCreateView, OrganizerUpdateView, OrganizerDeleteView, OrganizerDetailView
from qcos.base.views import CampListView, CampDetailView, CampDeleteView, CampUpdateView, FeeCreateView, FeeDeleteView
from qcos.base.views import FeeUpdateView, RegistrationCreateView, UserDetailView, UserProfileView, RegistrationListView
from qcos.base.views import UserHomeView, RegistrationDetailView, RegistrationUpdateView, RegistrationDeleteView
from qcos.base.views import RegestrationCheckinStep1View, RegestrationCheckinStep2View, RegestrationCheckinStep3View
from qcos.base.views import WorkshopCreateView, WorkshopUpdateView, WorkshopDeleteView, WorkshopListView
from qcos.base.views import WorkshopAnnotateView, WorkshopPrintView, WorkshopPrintBatchListView
from qcos.base.views import WorkshopPrintBatchDownloadView, ParticipantCheckInListView, ParticipantCheckInView
from qcos.base.views import RegistrationDownloadView

urlpatterns = [
	path('admin/', admin.site.urls),
	path('accounts/', include('django.contrib.auth.urls')),

	path("select2/", include("django_select2.urls")),

	path('base/diocese', DioceseListView.as_view(), name="list-diocese"),
	path('base/diocese/create', DioceseCreateView.as_view(), name="create-diocese"),
	path('base/diocese/<int:pk>/delete', DioceseDeleteView.as_view(), name="delete-diocese"),
	path('base/diocese/<int:pk>/detail', DioceseDetailView.as_view(), name="detail-diocese"),
	path('base/diocese/<int:pk>/update', DioceseUpdateView.as_view(), name="update-diocese"),

	path('base/diocese/<int:diocese_pk>/create_district', DistrictCreateView.as_view(), name="create-district"),
	path('base/district/<int:pk>/delete', DistrictDeleteView.as_view(), name="delete-district"),
	path('base/district/<int:pk>/detail', DistrictDetailView.as_view(), name="detail-district"),
	path('base/district/<int:pk>/update', DistrictUpdateView.as_view(), name="update-district"),

	path('base/district/<int:district_pk>/create_clan', ClanCreateView.as_view(), name="create-clan"),
	path('base/clan/<int:pk>/delete', ClanDeleteView.as_view(), name="delete-clan"),
	path('base/clan/<int:pk>/detail', ClanDetailView.as_view(), name="detail-clan"),
	path('base/clan/<int:pk>/update', ClanUpdateView.as_view(), name="update-clan"),

	path('', UserHomeView.as_view(), name='home-user'),
	path('base/user', UserListView.as_view(), name='list-user'),
	path('base/user/profile', UserProfileView.as_view(), name='profile-user'),
	path('base/user/create', UserCreateView.as_view(), name='create-user'),
	path('base/user/<int:pk>/detail', UserDetailView.as_view(), name='detail-user'),
	path('base/user/<int:pk>/update', UserUpdateView.as_view(), name='update-user'),
	path('base/user/<int:pk>/delete', UserDeleteView.as_view(), name='delete-user'),

	path('base/organizer', OrganizerListView.as_view(), name='list-organizer'),
	path('base/organizer/create', OrganizerCreateView.as_view(), name='create-organizer'),
	path('base/organizer/<int:pk>/update', OrganizerUpdateView.as_view(), name='update-organizer'),
	path('base/organizer/<int:pk>/delete', OrganizerDeleteView.as_view(), name='delete-organizer'),
	path('base/organizer/<int:pk>/detail', OrganizerDetailView.as_view(), name='detail-organizer'),

	path('base/camp', CampListView.as_view(), name='list-camp'),
	path('base/camp/create', CampCreateView.as_view(), name='create-camp'),
	path('base/camp/<int:pk>/update', CampUpdateView.as_view(), name='update-camp'),
	path('base/camp/<int:pk>/delete', CampDeleteView.as_view(), name='delete-camp'),
	path('base/camp/<int:pk>/detail', CampDetailView.as_view(), name='detail-camp'),

	path('base/camp/<int:camp_pk>/registrations/<int:pk>/update', RegistrationUpdateView.as_view(), name='update-registration'),
	path('base/camp/<int:camp_pk>/registrations/<int:pk>/delete', RegistrationDeleteView.as_view(), name='delete-registration'),
	path('base/camp/<int:camp_pk>/registrations/<int:pk>/detail', RegistrationDetailView.as_view(), name='detail-registration'),
	path('base/camp/<int:camp_pk>/registrations/<int:pk>/checkin/step1', RegestrationCheckinStep1View.as_view(), name='checkin-registration-step1'),
	path('base/camp/<int:camp_pk>/registrations/<int:pk>/checkin/step2', RegestrationCheckinStep2View.as_view(), name='checkin-registration-step2'),
	path('base/camp/<int:camp_pk>/registrations/<int:pk>/checkin/step3', RegestrationCheckinStep3View.as_view(), name='checkin-registration-step3'),
	path('base/camp/<int:camp_pk>/registrations/<int:pk>/workshop/add', WorkshopCreateView.as_view(), name='create-workshop'),
	path('base/camp/<int:camp_pk>/registrations/<int:registration_pk>/workshops/<int:pk>/update', WorkshopUpdateView.as_view(), name='update-workshop'),
	path('base/camp/<int:camp_pk>/registrations/<int:registration_pk>/workshops/<int:pk>/delete', WorkshopDeleteView.as_view(), name='delete-workshop'),
	path('base/camp/<int:camp_pk>/registrations/participants', ParticipantCheckInListView.as_view(), name='list-checkin-participants'),
	path('base/camp/<int:camp_pk>/registrations/<int:pk>/checkin-participants', ParticipantCheckInView.as_view(), name='checkin-participant'),
	path('base/camp/<int:camp_pk>/registrations/download', RegistrationDownloadView.as_view(), name='download-registration'),
	path('base/camp/<int:camp_pk>/workshops', WorkshopListView.as_view(), name='list-workshop'),
	path('base/camp/<int:camp_pk>/workshops/annotate', WorkshopAnnotateView.as_view(), name='annotate-workshop'),
	path('base/camp/<int:camp_pk>/workshops/print', WorkshopPrintView.as_view(), name='print-workshop'),
	path('base/camp/<int:camp_pk>/workshops/print/lists', WorkshopPrintBatchListView.as_view(), name='list-workshopprints'),
	path('base/camp/<int:camp_pk>/workshops/print/<int:batch_pk>/download', WorkshopPrintBatchDownloadView.as_view(), name='download-workshopprint'),
	path('base/camp/<int:camp_pk>/registrations', RegistrationListView.as_view(), name='list-registration'),
	path('base/camp/<int:camp_pk>/registrations/create', RegistrationCreateView.as_view(), name='create-registration'),


	path('base/camp/<int:camp_pk>/fee/create', FeeCreateView.as_view(), name='create-fee'),
	path('base/fee/<int:pk>/update', FeeUpdateView.as_view(), name='update-fee'),
	path('base/fee/<int:pk>/delete', FeeDeleteView.as_view(), name='delete-fee'),
]

src/qcos/base/models.py
from django.db.models import Model, ForeignKey, CASCADE, PROTECT, SET_NULL
from django.db.models.fields import CharField, SlugField, DateField, DecimalField, TextField, DateTimeField
from django.db.models.fields import EmailField, BooleanField, PositiveIntegerField
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import Group


class Diocese(Model):
	name = CharField(max_length=100)

	class Meta:
		default_permissions = ('view')

	def __str__(self):
		return self.name


class District(Model):
	name = CharField(max_length=100)
	diocese = ForeignKey(Diocese, on_delete=CASCADE)

	class Meta:
		default_permissions = ('view')

	def __str__(self):
		return self.name


class Clan(Model):
	name = CharField(max_length=100)
	district = ForeignKey(District, on_delete=CASCADE)

	class Meta:
		default_permissions = ('view')

	def __str__(self):
		return self.name


class Camp(Model):
	name = CharField(max_length=100)
	organizer = ForeignKey(Group, on_delete=CASCADE)
	description = CharField(max_length=500)
	slug = SlugField(max_length=100)
	start_date = DateField()
	end_date = DateField()

	class Meta:
		default_permissions = ()

	def registration_quantity(self):
		count = 0
		for fee in self.fee_set.all():
			count += fee.quantity()
		return count

	def present_participants(self):
		count = 0
		for registration in self.registration_set.all():
			count += registration.present_participants
		return count

	def registered_participants(self):
		count = 0
		for registration in self.registration_set.all():
			count += registration.registered_participants
		return count

	def total_price(self):
		price = 0
		for fee in self.fee_set.all():
			price += fee.total_price()
		return price

	def total_paid(self):
		paid = 0
		for registration in self.registration_set.all():
			paid += registration.paid
		return paid

	def __str__(self):
		return self.name


class Fee(Model):
	camp = ForeignKey(Camp, on_delete=CASCADE)
	name = CharField(max_length=100)
	price = DecimalField(decimal_places=2, max_digits=4)
	start_date = DateField(null=True, blank=True)
	end_date = DateField(null=True, blank=True)

	class Meta:
		default_permissions = ()

	def quantity(self):
		count = 0
		for ticket_info in self.ticketinfo_set.all():
			count += ticket_info.quantity
		return count

	def total_price(self):
		return self.quantity() * self.price

	def __str__(self):
		return self.name


class Registration(Model):
	clan = ForeignKey(Clan, on_delete=PROTECT)
	camp = ForeignKey(Camp, on_delete=CASCADE)
	telephone = CharField(max_length=100)
	contact_name = CharField(max_length=100)
	email = EmailField(max_length=100)
	comment = TextField(max_length=1000, null=True, blank=True)
	paid = DecimalField(decimal_places=2, max_digits=6, default=0)
	present_participants = PositiveIntegerField(default=0)
	#ToDo: Replace with ticket model
	registered_participants = PositiveIntegerField(default=0)
	#ToDo: Move into JsonField(?) and make this configurable
	rules_accepted = BooleanField(default=False)
	staff_confirmed = BooleanField(default=False)
	picture_rights = BooleanField(default=False)


	class Meta:
		default_permissions = ()

	def get_full_ticket_info(self):
		ticket_infos = list()
		fees = self.camp.fee_set.order_by('id')
		for fee in fees:
			data = dict()
			data['name'] = fee.name
			data['price'] = fee.price
			try:
				data['quantity'] = self.ticketinfo_set.get(fee=fee).quantity
			except ObjectDoesNotExist:
				data['quantity'] = 0
			data['full_price'] = data['quantity'] * fee.price
			ticket_infos.append(data)
		return ticket_infos

	def participants(self):
		participants = 0
		for info in self.ticketinfo_set.all():
			participants += info.quantity
		return participants

	def get_price(self):
		price = 0
		for info in self.ticketinfo_set.all():
			price += (info.fee.price * info.quantity)
		return price

	def get_ticket_infos(self):
		ticket_infos = list()
		fees = self.camp.fee_set.order_by('id')
		for fee in fees:
			try:
				info = self.ticketinfo_set.get(fee=fee).quantity
			except ObjectDoesNotExist:
				info = 0
			ticket_infos.append(info)
		return ticket_infos


class TicketInfo(Model):
	registration = ForeignKey(Registration, on_delete=CASCADE)
	fee = ForeignKey(Fee, on_delete=PROTECT)
	quantity = PositiveIntegerField(default=0)

	class Meta:
		default_permissions = ()

	def price(self):
		return self.quantity * self.fee.price

	def __str__(self):
		return str(self.quantity)


class Ticket(Model):
	ticket_info = ForeignKey(TicketInfo, on_delete=PROTECT)
	registered = DateTimeField(null=True)
	issued = BooleanField()

	class Meta:
		default_permissions = ()

WORKSHOP_STATUS=(
	("OK", "Workshop OK"),
	("FE", "Workshop fehlt"),
	("NO", "Workshop nicht OK"),
	("UN", "Workshop unklar"),
)

class WorkshopPrintBatch(Model):
	created = DateTimeField(auto_now_add=True)
	camp = ForeignKey(Camp, on_delete=CASCADE)


class Workshop(Model):
	registration = ForeignKey(Registration, on_delete=CASCADE)
	name = CharField(max_length=100)
	description = TextField(max_length=1000, null=True, blank=True)
	printed = ForeignKey(WorkshopPrintBatch, null=True, on_delete=SET_NULL)
	annotated_id = PositiveIntegerField(null=True)
	status = CharField(max_length=2, choices=WORKSHOP_STATUS, default="FE")

	def __str__(self):
		return self.name

src/qcos/base/forms.py
from django.forms import Form, ModelForm, ModelMultipleChoiceField
from django.forms import modelformset_factory, inlineformset_factory
from django.forms.fields import CharField, EmailField, MultipleChoiceField, BooleanField
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from django_select2.forms import Select2MultipleWidget
from qcos.base.models import TicketInfo, Registration
from django.utils.translation import gettext as _

class SignUpForm(UserCreationForm):
	first_name = CharField(max_length=30, required=False, help_text='Optional.')
	last_name = CharField(max_length=30, required=False, help_text='Optional.')
	email = EmailField(max_length=254, help_text='Required. Inform a valid email address.')

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email',)


class OrganizerForm(ModelForm):
	members = ModelMultipleChoiceField(queryset=User.objects.all(), widget=Select2MultipleWidget, required=False)

	class Meta:
		model = Group
		fields = ('name',)

	def __init__(self, *args, **kwargs):
		self.group = kwargs['instance']
		initial = kwargs.pop('initial', dict())
		if self.group is not None:
			initial['members'] = [x for x in User.objects.filter(groups=self.group)]
		kwargs['initial'] = initial
		super(OrganizerForm, self).__init__(*args, **kwargs)

	def save(self, commit=True):
		group = super(OrganizerForm, self).save(commit=commit)
		for user in group.user_set.all():
			group.user_set.remove(user)
		for user in self.cleaned_data['members']:
			group.user_set.add(user)
		group.save()
		return group


class TicketInfoForm(ModelForm):
	class Meta:
		model = TicketInfo
		fields = ('quantity',)


class RegistrationForm(ModelForm):
	class Meta:
		model = Registration
		fields = ('clan', 'contact_name', 'email', 'telephone', 'comment')
		# ToDo: add chained select2

#class TicketInfoFormSet(BaseFormSet):
#TicketInfoFormSet = inlineformset_factory()


class CheckInFormStep1(ModelForm):
	class Meta:
		model = Registration
		fields = ('paid', 'present_participants', 'comment')


class CheckInFormStep2(ModelForm):
	class Meta:
		model = Registration
		fields = ('rules_accepted', 'picture_rights', 'staff_confirmed')
	#signature = BooleanField(required=True, label="Lagerregeln anerkannt",
	#						 help_text="Lagerreglen anerkannt und unterschrieben")
	#dsgvo = BooleanField(required=True, label="Formular für die Bildrechte abgegeben",
	#					 help_text="Formular für die Bildrechte abgegeben und dementsprechend Bändchen herausgegeben")
	#staff_confirmation = BooleanField(required=True, label="Formular für Bestätigung über den Einsatzes geeigneten Personals",
	#					 help_text="Formular für die Bestätigung über den Einsatzes geeigneten Personals")
	trash_bags = BooleanField(required=True, label="Mülltüten ausgegeben",
						 help_text="Mülltüten ausgegeben 1 x Gelber Sack und 1 x Blauer Sack")


class WorkshopAnnotateForm(Form):
	annotate = BooleanField(required=True, label=_("Annotate all workshop with status ok"))


class WorkshopPrintForm(Form):
	generate_batch = BooleanField(required=True, label=_("Generate a print batch for all unprinted workshops"))

src/qcos/base/templates/base/camp_confirm_delete.html
{% extends 'confirm_delete.html' %}
{% load i18n %}
{% block base_active %}active{% endblock %}
{% block title %}{% trans "Delete camp" %}{% endblock %}
{% block type %}{% trans "Camp" %}{% endblock %}

src/qcos/base/templates/base/checkin_step2.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% block base_active %}active{% endblock %}
{% block title %}{% blocktrans %}Checkin for {{ clan }} for {{ camp }}{% endblocktrans %}{% endblock %}
{% block header %}{% blocktrans %}Checkin for {{ clan }} for {{ camp }}{% endblocktrans %}{% endblock %}
{% block actions %}
{% endblock %}
{% block body %}
<h2>{% trans "Check in" %}</h2>
{% bootstrap_form_errors form %}
<form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans "Next" %}</button>
    {% endbuttons %}
</form>
{% endblock %}

src/qcos/base/templates/base/checkin_step3.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% block base_active %}active{% endblock %}
{% block title %}{% blocktrans %}Checkin for {{ clan }} for {{ camp }}{% endblocktrans %}{% endblock %}
{% block header %}{% blocktrans %}Checkin for {{ clan }} for {{ camp }}{% endblocktrans %}{% endblock %}
{% block actions %}
{% endblock %}
{% block body %}
<h2>{% trans "Workshops" %}</h2>
		<table class="table table-striped">
			<thead>
				<tr>
					<th scope="col">{% trans "Name" %}</th>
					<th scope="col">{% trans "Description" %}</th>
					<th scope="col">{% trans "Status" %}</th>
					<th scope="col">{% trans "Number" %}</th>
					<th scope="col">{% trans "Printed" %}</th>
				</tr>
			</thead>
			<tbody>
				{% for workshop in registration.workshop_set.all %}
					<tr>
						<th scope="row">{{ workshop.name }}</th>
						<td>{{ workshop.desciption }}</td>
						<td>{{ workshop.get_status_display }}</td>
						<td>{% if workshop.annotated_id %}{{ workshop.annotated_id }}{% else %}Noch nicht vergeben{% endif %}</td>
						<td>{% if workshop.printed %}Ja{% else %}Nein{% endif %}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
    {% buttons %}
        <a href="{% url 'list-registration' camp.pk %}"><button type="button" class="btn btn-primary">Zurück zur Übersicht</button></a>
        <a href="{% url 'detail-registration' camp.pk registration.pk %}"><button type="button" class="btn btn-primary">Workshops bearbeiten</button></a>
    {% endbuttons %}
{% endblock %}

src/qcos/base/templates/base/clan_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block base_active %}active{% endblock %}
{% load bootstrap4 %}

{% block title %}{% blocktrans %}District {{ district }} - {{ mode }} Clan{% endblocktrans %}{% endblock %}
{% block header %}{% blocktrans %}District {{ district }} - {{ mode }} Clan{% endblocktrans %}{% endblock %}

{% block body %}
{% bootstrap_form_errors form %}
<form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
    {% endbuttons %}
</form>
{% endblock %}

src/qcos/base/templates/base/diocese_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block base_active %}active{% endblock %}
{% block title %}{% trans "Diocese" %} {{ object.name }}{% endblock %}
{% block header %}{% trans "Diocese" %} {{ object.name }}{% endblock %}
{% block actions %}
	<a href="{% url 'create-district' object.pk %}" class="btn btn-default btn-sm btn-favorite" role="button">
		{% trans "Add District" %}<span class="fas fa-plus"></span>
	</a>
{% endblock %}

{% block body %}
{% if object.district_set.all %}
	<table class="table table-striped">
		<thead>
			<tr>
				<th scope="col">{% trans "District" %}</th>
				<th scope="col">{% trans "View" %}</th>
				<th scope="col">{% trans "Edit" %}</th>
				<th scope="col">{% trans "Delete" %}</th>
			</tr>
		</thead>
		<tbody>
			{% for district in object.district_set.all %}
				<tr>
					<th scope="row">{{ district.name }}</th>
					<td><a href="{% url 'detail-district' district.pk %}" class="btn btn-primary btn-sm" role="button">{% trans "View" %}</a></td>
					<td><a href="{% url 'update-district' district.pk %}" class="btn btn-primary btn-sm" role="button">{% trans "Edit" %}</a></td>
					<td><a href="{% url 'delete-district' district.pk %}" class="btn btn-default btn-sm" role="button">
            	         <span class="fas fa-trash"></span>
							</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<h2>{% trans "There are no districts in this diocese" %}</h2>
{% endif %}
{% endblock %}

src/qcos/base/templates/base/diocese_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block base_active %}active{% endblock %}
{% block title %}{% blocktrans %}{{ mode }} Diocese{% endblocktrans %}{% endblock %}
{% block header %}{% blocktrans %}{{ mode }} Diocese{% endblocktrans %}{% endblock %}

{% block body %}
{% bootstrap_form_errors form %}
<form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
    {% endbuttons %}
</form>
{% endblock %}

src/qcos/base/templates/base/diocese_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block base_active %}active{% endblock %}
{% block title %}{% trans "Dioceses" %}{% endblock %}
{% block header %}{% trans "Dioceses" %}{% endblock %}
{% block actions %}
	<a href="{% url 'create-diocese' %}" class="btn btn-default btn-sm btn-favorite" role="button">
		{% trans "Add Diocese" %}<span class="fas fa-plus"></span>
	</a>
{% endblock %}
{% block body %}
{% if object_list %}
	<table class="table table-striped">
		<thead>
			<tr>
				<th scope="col">{% trans "Diocese" %}</th>
				<th scope="col">{% trans "View" %}</th>
				<th scope="col">{% trans "Edit" %}</th>
				<th scope="col">{% trans "Delete" %}</th>
			</tr>
		</thead>
		<tbody>
			{% for diocese in object_list %}
				<tr>
					<th scope="row">{{ diocese.name }}</th>
					<td><a href="{% url 'detail-diocese' diocese.pk %}" class="btn btn-primary btn-sm" role="button">{% trans "View" %}</a></td>
					<td><a href="{% url 'update-diocese' diocese.pk %}" class="btn btn-primary btn-sm" role="button">{% trans "Edit" %}</a></td>
					<td><a href="{% url 'delete-diocese' diocese.pk %}" class="btn btn-default btn-sm" role="button">
						<span class="fas fa-trash"></span>
						</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endif %}
{% endblock %}

src/qcos/base/templates/base/fee_confirm_delete.html
{% extends 'confirm_delete.html' %}
{% load i18n %}
{% block base_active %}active{% endblock %}
{% block title %}{% trans "Delete fee from camp" %} "{{ object.camp }}"{% endblock %}
{% block type %}{% trans "the fee" %}{% endblock %}

src/qcos/base/templates/base/fee_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block base_active %}active{% endblock %}
{% load bootstrap4 %}

{% block title %}{% blocktrans %}Camp {{ camp }} - {{ mode }} Fee{% endblocktrans %}{% endblock %}
{% block header %}{% blocktrans %}Camp {{ camp }} - {{ mode }} Fee{% endblocktrans %}{% endblock %}

{% block body %}
{% bootstrap_form_errors form %}
<form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
    {% endbuttons %}
</form>
{% endblock %}

src/qcos/base/templates/base/workshop_annotate.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% block base_active %}active{% endblock %}
{% block title %}{% trans "Annotate workshops for" %} {{camp}}{% endblock %}
{% block header %}{% trans "Annotate workshops for" %} {{camp}}{% endblock %}
{% block body %}
<form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans "Go" %}</button>
    {% endbuttons %}
</form>
{% endblock %}

src/qcos/base/templates/base/workshop_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% block base_active %}active{% endblock %}
{% block title %}{% blocktrans %}Add workshop for {{ clan }} for {{ camp }}{% endblocktrans %}{% endblock %}
{% block header %}{% blocktrans %}Add workshop for {{ clan }} for {{ camp }}{% endblocktrans %}{% endblock %}
{% block actions %}
{% endblock %}
{% block body %}
<h2>{% trans "Add workshop" %}</h2>
{% bootstrap_form_errors form %}
<form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
    {% endbuttons %}
</form>
{% endblock %}

src/qcos/base/templates/base/workshopprintbatch_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block base_active %}active{% endblock %}
{% block title %}{% trans "Workshop print batches for" %} {{camp}}{% endblock %}
{% block header %}{% trans "Workshop print batches for" %} {{camp}}{% endblock %}
{% block body %}
{% if object_list %}
	<table class="table table-striped">
		<thead>
			<tr>
				<th scope="col">{% trans "Created" %}</th>
				<th scope="col">{% trans "Workshops" %}</th>
				<th scope="col">{% trans "Download" %}</th>
				<th scope="col">{% trans "Delete" %}</th>
			</tr>
		</thead>
		<tbody>
			{% for batch in object_list %}
				<tr>
					<th scope="row">{{ batch.created }}</th>
					<td>{{ batch.workshop_set.count }}</td>
					<td><a href="{% url 'download-workshopprint' camp.pk batch.pk %}" class="btn btn-default btn-sm" role="button">
						<span class="fas fa-download"></span>
						</a></td>
					<td><a href="{#% url 'delete-workshop' camp.pk workshop.registration.pk workshop.pk %#}" class="btn btn-default btn-sm" role="button">
						<span class="fas fa-trash"></span>
						</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
<h3>{% trans "There are no print batches for this camp" %}</h3>
{% endif %}
{% endblock %}